# Generated by Django 4.1.7 on 2023-06-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_venta', models.DateField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='VentasXProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.ventas')),
            ],
        ),
    ]
