# Generated by Django 4.1.7 on 2023-06-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
