# Generated by Django 4.1.7 on 2023-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_alter_cargos_options_alter_empleados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo logueo'),
        ),
    ]
