# Generated by Django 4.1.7 on 2023-06-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_empleados_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='clave',
            new_name='password',
        ),
    ]
