# Generated by Django 4.1.7 on 2023-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_productos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
