# Generated by Django 4.1.7 on 2023-06-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_compra', models.DateField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasXProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.compras')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos')),
            ],
        ),
    ]
