# Generated by Django 4.1.7 on 2023-06-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='comprasxproducto',
            options={'verbose_name_plural': 'Lista de productos por Compra'},
        ),
    ]
