# Generated by Django 4.1.7 on 2023-06-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'verbose_name_plural': 'Departamentos'},
        ),
    ]
